---
name: plasma-current-response
board: boards/red-pitaya
version: 0.1.1

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/current_response_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/Div_to_address_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/Profile_Sweep_v1_0 
  - instruments/plasma-current-response-Charlie-Final-Version/cores/input_control_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/Div_int_delay_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/manual_calibration_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/data_collector_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/acquire_trigger_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/clock_counter_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/output_mux_v1_0
  - instruments/plasma-current-response-Charlie-Final-Version/cores/delay_signal_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: dac
    offset: '0x40000000'
    range: 32K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - led
  - Switch
  - Temperature
  - ISat
  - Vfloating
  - Resistence
  - Calibration_offset
  - Calibration_scale
  - trigger
  - Time_in
  - Downsample

status_registers:
  - adc[n_adc]
  - Current
  - Bias
  - Time_out

parameters:
  fclk0: 166666667
  bram_addr_width: 13
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/plasma-current-response/expansion_connector.xdc

drivers:
  - ./PCS.hpp
  - server/drivers/common.hpp

# web:
#   - web/koheron.ts
#   - web/jquery.flot.d.ts
#   - ./web/pulse_generator.ts
#   - ./web/app.ts
#   - ./web/control.ts
#   - ./web/plot.ts
#   - ./web/index.html
#   - web/main.css
#   - web/navigation.ts
