---
name: mirror-langmuir-probe
board: boards/red-pitaya
version: 0.1.1

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/set_voltage_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/isat_calc_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/temp_calc_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/vfloat_calc_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/data_collector_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/acquire_trigger_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/moving_average_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/manual_calibration_v1_0
  - instruments/mirror-langmuir-probe-Charlie-Final-Version/cores/output_mux_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: adc_fifo
    offset: '0x43C10000'
    range: 64K

control_registers:
  - led
  - Trigger
  - Period
  - Acquisition_length
  - Scale_LB
  - Offset_LB
  - Scale_PC
  - Offset_PC

status_registers:
  - adc[n_adc]
  - Temperature
  - Isaturation
  - vFloat
  - Timestamp

parameters:
  fclk0: 166666667
  dac_width: 14
  adc_width: 14
  n_adc: 2

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc
  - instruments/mirror-langmuir-probe/expansion_connector.xdc

drivers:
  - ./MLP.hpp
  - server/drivers/common.hpp

# web:
#   - web/koheron.ts
#   - web/jquery.flot.d.ts
#   - ./web/pulse_generator.ts
#   - ./web/app.ts
#   - ./web/control.ts
#   - ./web/plot.ts
#   - ./web/index.html
#   - web/main.css
#   - web/navigation.ts